name: minimum_duration
description: A minimum duration utility for Dart.
version: 0.0.3
repository: https://github.com/andyhorn/minimum_duration

environment:
  sdk: ^3.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
